controller_joint_names:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    
# Joint trajectory controller
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6

  #state_publish_rate: 50 # Defaults to 50
  #action_monitor_rate: 20 # Defaults to 20

controller_list:
  - name: "/move_group/arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

Robot_IP: "172.31.1.147"
Robot_Port: 7000
